---
- name: Delploy jellyfin
  docker_container:
    name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart_policy: unless-stopped
    recreate: true
    container_default_behavior: no_defaults
    networks_cli_compatible: yes
    security_opts:
      - no-new-privileges:true
    volumes:
      - "{{ jellyfin_data_path }}/config:/config:rw"
      - "{{ mount_path }}/tv:/data/tvshows:rw"
      - "{{ mount_path }}/movies:/data/movies:rw"
    devices:
      - "/dev/dri:/dev/dri"
    network_mode: "{{ proxy_network_name }}"
    env:
      PUID: "{{ username }}"
      PGID: "{{ username }}"
      TZ: Europe/Warsaw
    labels:
      com.docker.compose.project: "jellyfin"
      traefik.enable: "true"
      traefik.http.routers.jellyfin.entrypoints: "https"
      traefik.http.routers.jellyfin.rule: "Host(`jellyfin.{{ domain }}`)"
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.tls.certresolver: "cloudflare"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
