---
- name: Delploy jellyfin
  community.docker.docker_container:
    name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    restart_policy: unless-stopped
    recreate: true
    container_default_behavior: no_defaults
    networks_cli_compatible: yes
    security_opts:
      - no-new-privileges:true
    ports:
      - "8096:8096"
    volumes:
      - "{{ jellyfin_data_path }}/config:/config:rw"
      - "{{ mount_path }}/library:/data/media:rw"
    devices:
      - "/dev/dri:/dev/dri"
    env:
      PUID: "{{ username }}"
      PGID: "{{ username }}"
      UMASK: "002"
      TZ: Europe/Warsaw
