---
- hosts: all
  become: yes

  roles:
    - role: system
    - role: samba
    - { role: docker, tags: docker }
    - { role: portainer, tags: portainer }
    - { role: traefik, tags: traefik }
    - { role: jellyfin, tags: jellyfin }
    - { role: arr-stack, tags: arr-stack }
