---
- name: Configuring samba shares
  template:
    src: homeserver_smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart smbd

- name: Allow Samba traffic in firewall
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "445"
    - "139"

- name: Recursively change ownership of a directory
  file:
    path: "{{ mount_path }}"
    state: directory
    recurse: yes
    owner: "{{ systemuser }}"
    group: "{{ systemgroup }}"
    mode: 0775
