---
- name: Install generic needed packages
  apt:
    name:
    - samba
    - samba-vfs-modules
    state: latest
    cache_valid_time: 3600

- name: Start samba service, if not started
  ansible.builtin.service:
    name: smbd
    state: started