version: "3.7"

services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Warsaw
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=true
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.55.0/24
      - VPN_CONF=wg0
      # - VPN_ADDITIONAL_PORTS
      - VPN_KEEP_LOCAL_DNS=false
      - PRIVOXY_ENABLED=false
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /home/kris/qBit/config:/config
      - /media/data/torrents/:/data/torrents/:rw
