---
- name: Create traefik directory
  file:
    path: "{{ traefik_data_path }}"
    state: directory

- name: Create traefik acme.json file
  file:
    path: "{{ traefik_data_path }}/acme.json"
    state: touch
    mode: 0600

- name: Add traefik.yml file
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_data_path }}/traefik.yml"

- name: Create config.yml file
  file:
    path: "{{ traefik_data_path }}/config.yml"
    state: touch

- name: Install apache2-utils to use htpasswd
  apt:
    name: apache2-utils
    state: present

- name: open ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    state: enabled
  with_items:
    - 80
    - 443
    - 8080

# sudo apt install apache2-utils
- name: Create traefik user
  command: |
    htpasswd -nbB "{{ traefik_user }}" "{{ traefik_password }}"
  register: traefik_user_password

- name: Add docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_data_path }}/docker-compose.yml"

- name: Run traefik service
  docker_compose:
    project_src: "{{ traefik_data_path }}"
    state: present
